### ISSUE TITLE
点击播放 albumArt会报空指针

### ISSUE THREAD

**Issue by 888ewe** [lizixian18/MusicLibrary#136]
点击播放，调用  StarrySky.with().getNowPlayingSongInfo();代码，会报一下空指针错误

java.lang.IllegalStateException: getBitmap(MediaMetadataC…t.METADATA_KEY_ALBUM_ART) must not be null
        at com.lzx.starrysky.control.StarrySkyPlayerControl.getSongInfoFromMediaMetadata(StarrySkyPlayerControl.kt:433)
        at com.lzx.starrysky.control.StarrySkyPlayerControl.getNowPlayingSongInfo(StarrySkyPlayerControl.kt:184)

**Comment by EspoirX** [comment]
感谢提出，已经修改，请用 2.2.7 版本
