### ISSUE TITLE
album报错

### ISSUE THREAD

**Issue by 888ewe** [lizixian18/MusicLibrary#137]
java.lang.IllegalStateException: getBitmap(MediaMetadataC…t.METADATA_KEY_ALBUM_ART) must not be null
    at com.lzx.starrysky.control.StarrySkyPlayerControl.getSongInfoFromMediaMetadata(StarrySkyPlayerControl.kt:433)
    at com.lzx.starrysky.control.StarrySkyPlayerControl.getNowPlayingSongInfo(StarrySkyPlayerControl.kt:184)
    at com.turamigo.www.ui.trips.fragment.GaodeMapFragment.onClick(GaodeMapFragment.java:299)
    at android.view.View.performClick(View.java:6329)
    at android.view.View$PerformClick.run(View.java:25004)
    at android.os.Handler.handleCallback(Handler.java:809)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:166)
    at android.app.ActivityThread.main(ActivityThread.java:7367)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by 888ewe** [comment]
日常眼瞎，没看到楼主已经更新了
