### ISSUE TITLE
playbackManager报错

### ISSUE THREAD

**Issue by 888ewe** [lizixian18/MusicLibrary#141]
kotlin.KotlinNullPointerException
        at com.lzx.starrysky.playback.manager.PlaybackManager.handlePlayRequest(PlaybackManager.kt:74)
        at com.lzx.starrysky.playback.manager.PlaybackManager$MediaSessionCallback.onPlayFromMediaId(PlaybackManager.kt:287)
        at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPlayFromMediaId(MediaSessionCompat.java:1410)
        at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPlayFromMediaId(MediaSessionCompatApi21.java:202)
        at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1362)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)****

**Comment by EspoirX** [comment]
已解决
