### ISSUE TITLE
快速点击播放/暂停 会引起崩溃

### ISSUE THREAD

**Issue by BatriderD** [lizixian18/MusicLibrary#161]
播放歌曲状态 连续点击播放暂停会崩溃
2020-05-10 10:19:30.243 16653-16760/cn.com.yuntutianxia.sacrifice E/ACodec: OMX/mediaserver died, signalling error!
2020-05-10 10:19:30.243 16653-16760/cn.com.yuntutianxia.sacrifice E/ACodec: signalError(omxError 0x8000100d, internalError -32)
2020-05-10 10:19:30.244 16653-16760/cn.com.yuntutianxia.sacrifice E/MediaCodec: Codec reported err 0xffffffe0, actionCode 0, while in state 6
2020-05-10 10:19:30.272 16653-16760/cn.com.yuntutianxia.sacrifice E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
2020-05-10 10:19:30.275 16653-16756/cn.com.yuntutianxia.sacrifice E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-05-10 10:19:30.277 16653-16760/cn.com.yuntutianxia.sacrifice E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
2020-05-10 10:19:30.281 16653-16760/cn.com.yuntutianxia.sacrifice E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
2020-05-10 10:19:30.281 16653-16760/cn.com.yuntutianxia.sacrifice E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
2020-05-10 10:19:30.282 16653-16760/cn.com.yuntutianxia.sacrifice E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 0
2020-05-10 10:19:30.296 16653-16756/cn.com.yuntutianxia.sacrifice E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2067)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onDisabled(MediaCodecAudioRenderer.java:542)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:983)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:771)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:742)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2020-05-10 10:19:30.303 16653-16653/cn.com.yuntutianxia.sacrifice E/EventLogger: playerFailed [10.55, 7.36, window=0]
    com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:359)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by EspoirX** [comment]
建议做下防抖

**Comment by BatriderD** [comment]
第一反应也是这个，多试过几次发现不是间隔太短，点击慢了次数多了还会偶现，当时出现后无论怎么慢操作甚至点一次都会有，后来再想复现还不容易。。一开始是自己直接使用MusicManager，后来发现调用demo里面的通知栏的的按钮也是会出现。
这有其他办法解决么？

**Comment by EspoirX** [comment]
MusicManager？你用的是哪个版本，现在已经没这个东西了

**Comment by BatriderD** [comment]
versionCode 219
        versionName "2.1.9"
确实时间长了， 我更新再试一下 
谢谢~

**Comment by EspoirX** [comment]
建议先更新到最新的再观察吧，毕竟一路升级已经改了很多问题了
