### ISSUE TITLE
MtaSDK.CaughtExp: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by loper7** [lizixian18/MusicLibrary#175]
```kotlin
MtaSDK.CaughtExp: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.lzx.starrysky.common.MediaSessionConnection$MediaControllerCallback.onPlaybackStateChanged(MediaSessionConnection.kt:232)
        at android.support.v4.media.session.MediaControllerCompat$Callback$MessageHandler.handleMessage(MediaControllerCompat.java:1119)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:7709)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
MtaSDK.CaughtExp: App uncaught exception end.
```

**Comment by EspoirX** [comment]
请用2.4.5版本，有问题欢迎进行反馈
