### ISSUE TITLE
收集到崩溃信息，版本2.4.4

### ISSUE THREAD

**Issue by zaaach** [lizixian18/MusicLibrary#185]
Thread Name: 'main'
Back traces starts.
kotlin.KotlinNullPointerException
    at com.lzx.starrysky.common.MediaSessionConnection$MediaControllerCallback.onPlaybackStateChanged(MediaSessionConnection.kt:29)
    at android.support.v4.media.session.MediaControllerCompat$Callback$MessageHandler.handleMessage(MediaControllerCompat.java:15)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:210)
    at android.app.ActivityThread.main(ActivityThread.java:7080)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
Back traces ends.

**Comment by EspoirX** [comment]
用最新版

**Comment by zaaach** [comment]
好的
