### ISSUE TITLE
 Unable to create service com.lzx.starrysky.service.MusicService. SecurityException: listen

### ISSUE THREAD

**Issue by raychong** [lizixian18/MusicLibrary#203]
这个问题会出现在Android 12

`

```
> Process: com.pentagon.babytahfiz, PID: 28764
>     java.lang.RuntimeException: Unable to create service com.lzx.starrysky.service.MusicService: java.lang.SecurityException: listen
>         at android.app.ActivityThread.handleCreateService(ActivityThread.java:4955)
>         at android.app.ActivityThread.access$1900(ActivityThread.java:310)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2302)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loopOnce(Looper.java:226)
>         at android.os.Looper.loop(Looper.java:313)
>         at android.app.ActivityThread.main(ActivityThread.java:8641)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

`
` 

     Caused by: java.lang.SecurityException: listen
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
        at android.os.Parcel.createException(Parcel.java:2421)
        at android.os.Parcel.readException(Parcel.java:2404)
        at android.os.Parcel.readException(Parcel.java:2346)
        at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenWithEventList(ITelephonyRegistry.java:1036)
        at android.telephony.TelephonyRegistryManager.listenFromListener(TelephonyRegistryManager.java:250)
        at android.telephony.TelephonyManager.listen(TelephonyManager.java:6798)
        at com.lzx.starrysky.service.MusicService.initTelephony(MusicService.kt:120)
        at com.lzx.starrysky.service.MusicService.initPlayerService(MusicService.kt:56)
        at com.lzx.starrysky.service.MusicService.onCreate(MusicService.kt:37)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4942)`

**Comment by DIPENG-XU** [comment]
同问，Android 12 出现这个问题。

**Comment by anaivez** [comment]
权限问题 添加权限即可
`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`

**Comment by EspoirX** [comment]
是的

**Comment by DIPENG-XU** [comment]
> 权限问题 添加权限即可 ` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> <uses-permission android:name="android.permission.READ_PHONE_STATE" /> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`

这个办法确实有效，感谢老铁，想请教是怎么定位到这里的，我想学习一下这种定位思路

**Comment by anaivez** [comment]
> > 权限问题 添加权限即可 ` <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" /> <uses-permission android:name="android.permission.READ_PHONE_STATE" /> <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`
> 
> 这个办法确实有效，感谢老铁，想请教是怎么定位到这里的，我想学习一下这种定位思路

Google
