### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by KunLL** [lizixian18/MusicLibrary#204]
版本是2.6.5
应用里引入过gsyVideoPlayer，也设置了android.enableDexingArtifactTransfrom=false，但是还是会崩溃

java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.upstream.DefaultHttpDataSourceFactory" on path: DexPathList[[zip file "/data/app/com.lc.matouqin-58pkQIkP7u2esWE0w-aj7g==/base.apk"],nativeLibraryDirectories=[/data/app/com.lc.matouqin-58pkQIkP7u2esWE0w-aj7g==/lib/arm64, /data/app/com.lc.matouqin-58pkQIkP7u2esWE0w-aj7g==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.lzx.starrysky.playback.ExoPlayback.buildDataSourceFactory(ExoPlayback.kt:275) 
        at com.lzx.starrysky.playback.ExoPlayback.createMediaSource(ExoPlayback.kt:206) 
        at com.lzx.starrysky.playback.ExoPlayback.play(ExoPlayback.kt:147) 
        at com.lzx.starrysky.manager.PlaybackManager$onPlayMusicImpl$1.onNext(PlaybackManager.kt:94) 
        at com.lzx.starrysky.intercept.InterceptorService.handlerInterceptor(InterceptorService.kt:18) 
        at com.lzx.starrysky.manager.PlaybackManager.onPlayMusicImpl(PlaybackManager.kt:88) 
        at com.lzx.starrysky.control.PlayerControl.playMusicImpl(PlayerControl.kt:145) 
        at com.lzx.starrysky.control.PlayerControl.playMusic(PlayerControl.kt:131)

**Comment by KunLL** [comment]
找到原因了，gsyVideoPlayer的exoplayer版本比starrySky高导致的

**Comment by boiyun** [comment]
> 找到原因了，gsyVideoPlayer的exoplayer版本比starrySky高导致的

兄弟，怎么解决的，我这也是这个错误

**Comment by KunLL** [comment]
> > 找到原因了，gsyVideoPlayer的exoplayer版本比starrySky高导致的
> 
> 兄弟，怎么解决的，我这也是这个错误

你比较一下starrySky里exoplayer的版本和gsyVideoPlayer里的exoplayer的版本，这两个版本得统一了，不然就会被覆盖；我这边是把gsyVideoPlayer的版本回退了，具体到哪个版本我也不记得了

**Comment by boiyun** [comment]
> > > 找到原因了，gsyVideoPlayer的exoplayer版本比starrySky高导致的
> > 
> > 
> > 兄弟，怎么解决的，我这也是这个错误
> 
> 你比较一下starrySky里exoplayer的版本和gsyVideoPlayer里的exoplayer的版本，这两个版本得统一了，不然就会被覆盖；我这边是把gsyVideoPlayer的版本回退了，具体到哪个版本我也不记得了

好的我处理一下，要么那边回退，要么这个升级，都得改代码，我搞一下
