### ISSUE TITLE
在api32上无法播放，没有任何反馈

### ISSUE THREAD

**Issue by ZXHHYJ** [lizixian18/MusicLibrary#207]
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err: java.lang.IllegalArgumentException: studio.mandysa.music: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err:     at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err:     at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err:     at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.utils.CommExtKt.getPendingIntent(CommExt.kt:81)
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.notification.SystemNotification.getPendingIntent(SystemNotification.kt:282)
2022-06-06 23:52:24.576 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.notification.SystemNotification.<init>(SystemNotification.kt:61)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.notification.SystemNotification.<init>(SystemNotification.kt:36)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.notification.NotificationManager$Companion$SYSTEM_NOTIFICATION_FACTORY$1.build(NotificationManager.kt:20)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.notification.NotificationManager.getSystemNotification(NotificationManager.kt:11)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.service.MusicServiceBinder.createNotification(MusicServiceBinder.kt:62)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.service.MusicServiceBinder.setNotificationConfig(MusicServiceBinder.kt:52)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.lzx.starrysky.StarrySky$serviceConnection$1.onServiceConnected(StarrySky.kt:398)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2077)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2110)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.os.Looper.loop(Looper.java:288)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7870)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
2022-06-06 23:52:24.577 19955-19955/studio.mandysa.music W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by EspoirX** [comment]
安卓12还没适配

**Comment by jarvan11** [comment]
华为nova9（HWMNA MNA-AL00）Android 12无法播放
