### ISSUE TITLE
最新版本Android 8.0 以上DeadObjectException

### ISSUE THREAD

**Issue by highBigger** [lizixian18/MusicLibrary#28]
06-07 16:20:29.409 24058-24058/com.pop.music W/System.err: android.os.DeadObjectException
06-07 16:20:29.410 24058-24058/com.pop.music W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:751)

**Comment by lizixian18** [comment]
怎么操作

**Comment by highBigger** [comment]
直接运行开始播第一首歌就这样。

**Comment by highBigger** [comment]
机型是小米mix2

**Comment by highBigger** [comment]
错误信息就是上面那样，就是开启了那个前台服务导致的。我去掉就好了
