### ISSUE TITLE
 android.os.DeadObjectException

### ISSUE THREAD

**Issue by tank2014gz** [lizixian18/MusicLibrary#35]
android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at com.lzx.musiclibrary.aidl.source.IPlayControl$Stub$Proxy.getCurrPlayingMusic(IPlayControl.java:883)
W:     at com.lzx.musiclibrary.manager.MusicManager.getCurrPlayingMusic(MusicManager.java:554)
      后台播放完一首音乐之后再次进入前台点击按钮进行播放时出现这种异常

**Comment by Layne2016** [comment]
解决了吗，我在考虑要不要用这个库

**Comment by lizixian18** [comment]
用的是哪个版本
