### ISSUE TITLE
音乐播放不了

### ISSUE THREAD

**Issue by Zhangxd77** [lizixian18/MusicLibrary#4]
通过接口形式获取了一个url,然后报错，这个歌是正常可以播放的，刚试过，代码是这么写的。并且先在applicaion中做了初始化
` SongInfo songInfo = new SongInfo();
                        songInfo.setSongId(audioStreamUrl);
                        songInfo.setSongUrl(audioStreamUrl);
                        MusicManager.get().playMusicByInfo(songInfo);`

![image](https://user-images.githubusercontent.com/20806535/37950049-c4b65aa4-31c9-11e8-9f55-52f49722caa8.png)

**Comment by lizixian18** [comment]
这个异常是我抛出来的，看来要考虑一下字段比较少的情况，你先这样解决先吧：
AlbumInfo albumInfo = new AlbumInfo();
albumInfo.setAlbumName(audioStreamUrl);
albumInfo.setAlbumCover("");
songInfo.setAlbumInfo(albumInfo);

设置一下 albumInfo，我会尽快兼容一下这方面的东西，谢谢反馈。

**Comment by Zhangxd77** [comment]
我这么写完能播了。然后我把APP退到后台，播了一两分钟后，抛出来个异常
`   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.io.EOFException
                                                                                        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.read(DefaultHttpDataSource.java:269)
                                                                                        at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:152)
                                                                                        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260)
                                                                                        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                                                        at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:547)
                                                                                        at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.readSample(Mp3Extractor.java:220)
                                                                                        at com.google.android.exoplayer2.extractor.mp3.Mp3Extractor.read(Mp3Extractor.java:190)
                                                                                        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
                                                                                        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                        at java.lang.Thread.run(Thread.java:841)`

**Comment by Zhangxd77** [comment]
麻烦你帮忙看下，这个是为什么，谢谢

**Comment by lizixian18** [comment]
好，我分析一下，你方便把播放链接给我试试吗

**Comment by Zhangxd77** [comment]
我能加一下你qq吗，我这个url有时效性，然后还有加密，我打断点然后把url给你，你拿去看只能这样可以吗
