### ISSUE TITLE
NullPointerException SystemNotification.java:177

### ISSUE THREAD

**Issue by windvip** [lizixian18/MusicLibrary#60]
java.lang.RuntimeException: Unable to stop service com.lzx.musiclibrary.MusicService@bb78282: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.lzx.musiclibrary.aidl.model.SongInfo.getSongCover()' on a null object reference
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3725)
	at android.app.ActivityThread.-wrap27(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.lzx.musiclibrary.aidl.model.SongInfo.getSongCover()' on a null object reference
	at com.lzx.musiclibrary.notification.SystemNotification.createNotification(SystemNotification.java:177)
	at com.lzx.musiclibrary.notification.SystemNotification.updateViewStateAtPause(SystemNotification.java:129)
	at com.lzx.musiclibrary.control.PlayControlImpl.onPlaybackStateUpdated(PlayControlImpl.java:349)
	at com.lzx.musiclibrary.playback.PlaybackManager.updatePlaybackState(PlaybackManager.java:299)
	at com.lzx.musiclibrary.playback.PlaybackManager.handleStopRequest(PlaybackManager.java:93)
	at com.lzx.musiclibrary.control.PlayControlImpl.stopMusic(PlayControlImpl.java:172)
	at com.lzx.musiclibrary.control.PlayControl.stopMusic(PlayControl.java:274)
	at com.lzx.musiclibrary.MusicService.onDestroy(MusicService.java:93)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3707)
	... 8 more

**Comment by lizixian18** [comment]
已解决
