### ISSUE TITLE
SimpleExoPlayer Player is accessed on the wrong thread

### ISSUE THREAD

**Issue by dxsdyhm** [lizixian18/MusicLibrary#93]
```
W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://google.github.io/ExoPlayer/faqs.html#what-do-player-is-accessed-on-the-wrong-thread-warnings-mean
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1190)
        at com.google.android.exoplayer2.SimpleExoPlayer.removeListener(SimpleExoPlayer.java:841)
        at com.lzx.musiclibrary.playback.player.ExoPlayback.releaseResources(ExoPlayback.java:128)
        at com.lzx.musiclibrary.playback.player.ExoPlayback.stop(ExoPlayback.java:147)
        at com.lzx.musiclibrary.playback.PlaybackManager.handleStopRequest(PlaybackManager.java:91)
        at com.lzx.musiclibrary.control.BasePlayControl.reset(BasePlayControl.java:244)
        at com.lzx.musiclibrary.aidl.source.IPlayControl$Stub.onTransact(IPlayControl.java:282)
        at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by EspoirX** [comment]
This issue has been fixed in the new version

**Comment by javakam** [comment]
怎么解决的呢？😓

**Comment by EspoirX** [comment]
你还会有这问题？

**Comment by bctpl** [comment]
Yes I 'm facing this issue I'm using latest version 2.10.0 of EXO player library 

I am using exoplayer in [JiaoZiVideoPlayer](https://github.com/lipangit/JiaoZiVideoPlayer).

I am getting error in this line `final int percent = simpleExoPlayer.getBufferedPercentage();`

```Java
private class onBufferingUpdate implements Runnable {
      @Override
      public void run() {
      if (simpleExoPlayer != null) {
                final int percent = simpleExoPlayer.getBufferedPercentage();
                handler.post(() -> jzvd.setBufferProgress(percent));
                if (percent < 100) {
                    handler.postDelayed(callback, 300);
                } else {
                    handler.removeCallbacks(callback);
                }
            }
         }
}
```

**Whole file is atteched**
[JZMediaExo.txt](https://github.com/EspoirX/StarrySky/files/3197308/JZMediaExo.txt)
