### ISSUE TITLE
Persisting actions failed.

### ISSUE THREAD

**Issue by luneice** [lizixian18/MusicLibrary#98]
感谢作者提供的框架，在使用框架时，为了缓存媒体时，需要设置缓存的路径，指定后出现了错误。
```
E/DownloadManager: Persisting actions failed.
    java.io.IOException: Couldn't create directory /storage/emulated/0/ExoCacheDir/actions
        at com.google.android.exoplayer2.util.AtomicFile.startWrite(AtomicFile.java:106)
        at com.google.android.exoplayer2.offline.ActionFile.store(ActionFile.java:84)
        at com.google.android.exoplayer2.offline.DownloadManager.lambda$saveActions$2(DownloadManager.java:503)
        at com.google.android.exoplayer2.offline.-$$Lambda$DownloadManager$SgHHqKrgOJ8vvRnakgUybwmDe2w.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/ExoCacheDir/actions (No such file or directory)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
        at com.google.android.exoplayer2.util.AtomicFile$AtomicFileOutputStream.<init>(AtomicFile.java:158)
        at com.google.android.exoplayer2.util.AtomicFile.startWrite(AtomicFile.java:102)
        at com.google.android.exoplayer2.offline.ActionFile.store(ActionFile.java:84) 
        at com.google.android.exoplayer2.offline.DownloadManager.lambda$saveActions$2(DownloadManager.java:503) 
        at com.google.android.exoplayer2.offline.-$$Lambda$DownloadManager$SgHHqKrgOJ8vvRnakgUybwmDe2w.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:754) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:163) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
```
权限配置为
```
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"
        tools:ignore="ProtectedPermissions" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

**Comment by EspoirX** [comment]
是初始化创建文件的时候蹦还是读取的时候蹦，代码看看？

**Comment by luneice** [comment]
相关代码如下：
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.xxx);
        RelativeLayout relativeLayout = findViewById(R.id.xxx);
        relativeLayout.setOnClickListener(this);

        MusicManager.initMusicManager(this);
        MediaSessionConnection.getInstance(this).connect();

        //配置通知栏
        NotificationConstructor constructor = new NotificationConstructor.Builder()
                .bulid();
        MusicManager.getInstance().setNotificationConstructor(constructor);
        String destFileDir = Environment.getExternalStorageDirectory().getAbsolutePath() + "/ExoCacheDir";
        ExoDownload.getInstance().setOpenCache(true); //打开缓存开关
        ExoDownload.getInstance().setShowNotificationWhenDownload(true);
        ExoDownload.getInstance().setCacheDestFileDir(destFileDir); //设置缓存文件夹

        ......
    }
```

**Comment by EspoirX** [comment]
有点尴尬，我现在在山里没网调不了，你看看你的系统是不是8.0，是不是需要动态权限申请？或者你跑一下我的demo看看？看错误信息是创建不了文件夹，所以读取的时候找不到文件，问题应该就是出在 File 相关的操作，或者debug一下？

**Comment by luneice** [comment]
demo 跑了一下，demo 没有缓存，播放音乐时需要联网重新下载。

**Comment by EspoirX** [comment]
排查了一下，发现创建缓存文件夹的时候只是new File()了，忘记 file.mkdirs() 了，应该是这个问题吧，可以用最新的版本试试，已提交
